use older git resource
trying this because we saw
```
error: pathspec 'src/github.com/docker/distribution' did not match any file(s) known to git.
```

in
https://ci.concourse-ci.org/teams/main/pipelines/release-4.2.x/jobs/atc/builds/77

Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>
Co-authored-by: Jamie Klassen <cklassen@pivotal.io>